package dev.noelsrocha.aluvery.ui.theme

import androidx.compose.ui.graphics.Color

// Light Scheme
val LightPrimary = Color(0xFF006876)
val LightOnPrimary = Color(0xFFffffff)
val LightPrimaryContainer = Color(0xFFa0efff)
val LightOnPrimaryContainer = Color(0xFF001f25)
val LightSecondary = Color(0xFF984800)
val LightOnSecondary = Color(0xFFffffff)
val LightSecondaryContainer = Color(0xFFffdbc8)
val LightOnSecondaryContainer = Color(0xFF311300)
val LightTertiary = Color(0xFF006495)
val LightOnTertiary = Color(0xFFffffff)
val LightTertiaryContainer = Color(0xFFcbe6ff)
val LightOnTertiaryContainer = Color(0xFF001e30)
val LightError = Color(0xFFba1a1a)
val LightOnError = Color(0xFFffffff)
val LightErrorContainer = Color(0xFFffdad6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFfffbff)
val LightOnBackground = Color(0xFF251a00)
val LightSurface = Color(0xFFfffbff)
val LightOnSurface = Color(0xFF251a00)
val LightOutline = Color(0xFF6f797b)
val LightSurfaceVariant = Color(0xFFdbe4e6)
val LightOnSurfaceVariant = Color(0xFF3f484a)

// Dark Scheme
val DarkPrimary = Color(0xFF51d7ee)
val DarkOnPrimary = Color(0xFF00363e)
val DarkPrimaryContainer = Color(0xFF004e59)
val DarkOnPrimaryContainer = Color(0xFFa0efff)
val DarkSecondary = Color(0xFFffb689)
val DarkOnSecondary = Color(0xFF512300)
val DarkSecondaryContainer = Color(0xFF733500)
val DarkOnSecondaryContainer = Color(0xFFffdbc8)
val DarkTertiary = Color(0xFF8fcdff)
val DarkOnTertiary = Color(0xFF003450)
val DarkTertiaryContainer = Color(0xFF004b71)
val DarkOnTertiaryContainer = Color(0xFFcbe6ff)
val DarkError = Color(0xFFffb4a9)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000a)
val DarkOnErrorContainer = Color(0xFFffdad6)
val DarkBackground = Color(0xFF251a00)
val DarkOnBackground = Color(0xFFfffbff)
val DarkSurface = Color(0xFF251a00)
val DarkOnSurface = Color(0xFFfffbff)
val DarkOutline = Color(0xFF8b938e)
val DarkSurfaceVariant = Color(0xFF3f484a)
val DarkOnSurfaceVariant = Color(0xFFdbe4e6)